name: Build

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies
      - run: npm ci
        working-directory: ./webpack

      # Build and output webpack stats to artifacts/webpack-stats.json
      - run: npm run build --if-present
        working-directory: ./webpack

      # Upload webpack artifacts/webpack-stats.json to use on relative-ci.yaml
      - name: Upload webpack stats artifact
        uses: relative-ci/agent-upload-artifact-action@v1
        with:
          webpackStatsFile: ./webpack/artifacts/webpack-stats.json
